//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConEmuIntegration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConEmuIntegration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;key name=&quot;Software&quot;&gt;
        ///    &lt;key name=&quot;ConEmu&quot;&gt;
        ///        &lt;key name=&quot;.Vanilla&quot; modified=&quot;2016-07-04 23:35:45&quot; build=&quot;160619&quot;&gt;
        ///            &lt;value name=&quot;StartType&quot; type=&quot;hex&quot; data=&quot;02&quot;/&gt;
        ///            &lt;value name=&quot;CmdLine&quot; type=&quot;string&quot; data=&quot;&quot;/&gt;
        ///            &lt;value name=&quot;StartTasksFile&quot; type=&quot;string&quot; data=&quot;&quot;/&gt;
        ///            &lt;value name=&quot;StartTasksName&quot; type=&quot;string&quot; data=&quot;{Shells::PowerShell}&quot;/&gt;
        ///            &lt;value name=&quot;StartFarFolders&quot; type=&quot;hex&quot; data=&quot;00&quot;/&gt;
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConEmu {
            get {
                return ResourceManager.GetString("ConEmu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string SettingsConEmuPath {
            get {
                return ResourceManager.GetString("SettingsConEmuPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default task.
        /// </summary>
        internal static string SettingsDefaultTask {
            get {
                return ResourceManager.GetString("SettingsDefaultTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML configuration.
        /// </summary>
        internal static string SettingsXMLConfiguration {
            get {
                return ResourceManager.GetString("SettingsXMLConfiguration", resourceCulture);
            }
        }
    }
}
